version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: irysbase-postgres
    environment:
      POSTGRES_USER: irysbase
      POSTGRES_PASSWORD: password
      POSTGRES_DB: irysbase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U irysbase"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: irysbase-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  vector-db:
    image: qdrant/qdrant
    container_name: irysbase-vector-db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  qdrant_data: